#!/bin/sh
# Copyright (C) 2014 Julien Bonjean <julien@bonjean.info>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

INTERFACE="${BLOCK_INSTANCE:-wlp3s0}"

state="$(cat /sys/class/net/$INTERFACE/operstate)"

if [ "$state" == "up" ]; then
        IP_ADDR="$(ip addr show wlp3s0 | grep "inet " | awk '{print $2}' | cut -d . -f 2-)"
        echo $IP_ADDR
        echo $IP_ADDR
        echo "#FFFF00"
        exit 0
elif [ "$(cat /sys/class/net/enp0s20u2u4u1i5/operstate)" == "up" ]; then
        IP_ADDR="$(ip addr show enp0s20u2u4u1i5 | grep "inet " | awk '{print $2}' | cut -d . -f 2-)"
        echo $IP_ADDR
        echo $IP_ADDR
        echo "#FFFF00"
        exit 0
elif [ "$(cat /sys/class/net/usb0/operstate)" == "up" ]; then
    IP_ADDR="$(ip addr show usb0 | grep "inet " | awk '{print $2}' | cut -d . -f2-)"
    echo $IP_ADDR
    echo $IP_ADDR
    echo "#FFFF00"
    exit 0
else
       	echo "down"
	echo "down"
	echo "#FF0000"
	exit 0
fi

# speed="$(cat /sys/class/net/$INTERFACE/speed 2> /dev/null)"

# ipaddr="$(ip addr show $INTERFACE | perl -n -e'/inet (.+)\// && print $1')"
# ipaddr="${ipaddr:-0.0.0.0}"

# full text
# echo -n "$ipaddr"
# [ -n "$speed" ] && echo " ($speed Mbits/s)" || echo

# short text
# echo "$ipaddr"
# echo $INTERFACE: `echo $state | tr '[:lower:]' '[:upper:]'`
